runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:T1vsw+PfxbwkSI/gP+YbQbnWFkbmAjM+2LnGUjR89WA=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: twitty
  DB_USERNAME: twitty
  DB_PASSWORD: 1111111
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/twitty-273410:asia-southeast1:database-twitty"

